### ISSUE TITLE
there's something wrong with the installation guide

### ISSUE THREAD

**Issue by djahma** [fireball-x/editor-framework#54]
Hi there, I couldn't manage to start the demo app following the installation guide, maybe because I am totally new to all this node and js thing in general, or maybe because it needs to be updated.

###### First installation method
I cloned the repo with `git clone https://github.com/fireball-x/editor-framework.git
`, then `cd editor-framework/` and eventually did `npm bootstrap`. But all I got was the help guide for npm, telling me there is no 'bootstrap' command.

###### Second installation method
So I tried the second installation process: `mkdir testApp` then `cd testApp` and finally `npm install fireball-x/editor-framework`. All went smoothly so I could do `cd ./node_modules/editor-framework/
` followed by `npm start` which triggered the following error message:

```
gman@thinkpad:~/Development/Electron/testApp/node_modules/editor-framework$ npm start

> editor-framework@0.3.13 start /home/gman/Development/Electron/testApp/node_modules/editor-framework
> gulp run

[19:28:46] Using gulpfile ~/Development/Electron/testApp/node_modules/editor-framework/gulpfile.js
[19:28:46] Starting 'run'...
execvp(): No such file or directory

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)

npm ERR! editor-framework@0.3.13 start: `gulp run`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the editor-framework@0.3.13 start script.
npm ERR! This is most likely a problem with the editor-framework package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp run
npm ERR! You can get their info via:
npm ERR!     npm owner ls editor-framework
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.19.0-23-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/gman/Development/Electron/testApp/node_modules/editor-framework
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read /usr/share/doc/nodejs/README.Debian
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/gman/Development/Electron/testApp/node_modules/editor-framework/npm-debug.log
npm ERR! not ok code 0
```
###### What worked...
...was `gman@thinkpad:~/Development/Electron/testApp/node_modules/editor-framework$ electron .
`

**Comment by jwu** [comment]
It was a mistake in README. the `npm bootstrap` should change to `npm install`. I just fixed this, please try it again.

**Comment by jwu** [comment]
Hi @nantas , would you mind to review the REAME to confirm this?

**Comment by nantas** [comment]
@djahma I couldn't reproduce on my machine.
Could you please tell me what's platform you're running? Also please exam if there's any error during `npm install` process. Thanks!

**Comment by djahma** [comment]
hi nantas. Running on Ubuntu 15.04 amd64. Redoing the first method with npm install, I get no error but a few warnings:
```
gman@thinkpad:~/Development/Electron/editor-framework$ npm install
npm WARN engine firedoc@1.9.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN optional dep failed, continuing fsevents@0.3.6
npm WARN engine hawk@3.1.0: wanted: {"node":">=0.10.32"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine hawk@3.1.0: wanted: {"node":">=0.10.32"} (current: {"node":"0.10.25","npm":"1.4.21"})
```
Then moving into editor-framework dir and `npm start` I get the same error as with second method.

Eventually, doing `gman@thinkpad:~/Development/Electron/editor-framework$ electron .` I get plenty of errors I did not have at the time of my previous post:
```
gman@thinkpad:~/Development/Electron/editor-framework$ electron .
[12613:0727/122140:ERROR:browser_main_loop.cc(173)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[...]
[12613] Prepare for watching packages
[12613] Error: Package Watcher Error: watch ENOSPC
    at EventEmitter.<anonymous> (/home/gman/Development/Electron/editor-framework/core/editor-init.js:492:16)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at EventEmitter.FSWatcher._handleError (/home/gman/Development/Electron/editor-framework/node_modules/chokidar/index.js:168:10)
    at createFsWatchInstance (/home/gman/Development/Electron/editor-framework/node_modules/chokidar/lib/nodefs-handler.js:39:5)
    at setFsWatchListener (/home/gman/Development/Electron/editor-framework/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at EventEmitter.NodeFsHandler._watchWithNodeFs (/home/gman/Development/Electron/editor-framework/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at EventEmitter.NodeFsHandler._handleDir (/home/gman/Development/Electron/editor-framework/node_modules/chokidar/lib/nodefs-handler.js:403:23)
    at EventEmitter.<anonymous> (/home/gman/Development/Electron/editor-framework/node_modules/chokidar/lib/nodefs-handler.js:450:19)
[12613] Error: Package Watcher Error: watch ENOSPC
    at EventEmitter.<anonymous> (/home/gman/Development/Electron/editor-framework/core/editor-init.js:492:16)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at EventEmitter.FSWatcher._handleError (/home/gman/Development/Electron/editor-framework/node_modules/chokidar/index.js:168:10)
    at createFsWatchInstance (/home/gman/Development/Electron/editor-framework/node_modules/chokidar/lib/nodefs-handler.js:39:5)
    at setFsWatchListener (/home/gman/Development/Electron/editor-framework/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at EventEmitter.NodeFsHandler._watchWithNodeFs (/home/gman/Development/Electron/editor-framework/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at EventEmitter.NodeFsHandler._handleDir (/home/gman/Development/Electron/editor-framework/node_modules/chokidar/lib/nodefs-handler.js:403:23)
    at EventEmitter.<anonymous> (/home/gman/Development/Electron/editor-framework/node_modules/chokidar/lib/nodefs-handler.js:450:19)
[12613] Error: Package Watcher Error: watch ENOSPC
    at EventEmitter.<anonymous> (/home/gman/Development/Electron/editor-framework/core/editor-init.js:492:16)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at EventEmitter.FSWatcher._handleError (/home/gman/Development/Electron/editor-framework/node_modules/chokidar/index.js:168:10)
    at createFsWatchInstance (/home/gman/Development/Electron/editor-framework/node_modules/chokidar/lib/nodefs-handler.js:39:5)
    at setFsWatchListener (/home/gman/Development/Electron/editor-framework/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at EventEmitter.NodeFsHandler._watchWithNodeFs (/home/gman/Development/Electron/editor-framework/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at EventEmitter.NodeFsHandler._handleDir (/home/gman/Development/Electron/editor-framework/node_modules/chokidar/lib/nodefs-handler.js:403:23)
    at EventEmitter.<anonymous> (/home/gman/Development/Electron/editor-framework/node_modules/chokidar/lib/nodefs-handler.js:450:19)
[...]
```
...still it works, I get the demo app running.

**Comment by nantas** [comment]
Please give us some time to setup a Ubuntu test machine. We haven't done testing on that platform yet.

**Comment by djahma** [comment]
ok, at last I've found the trouble. `Error: Package Watcher Error: watch ENOSPC` was a systemd issue.
I added `fs.inotify.max_user_watches = 81920` to /etc/sysctl.conf then did `sudo sysctl -p` to read the new value and the error disappeared.

At present I have troubles creating an app with the framework but I guess you can close this issue now.
