### ISSUE TITLE
npm install will report nan not find

### ISSUE THREAD

**Issue by jwu** [fireball-x/editor-framework#59]
Currently if I use `npm install` it will report `can't find the moudle nan` error message. This is relate with firedoc. To solve this problem, I have manually add nan in dependencies in package.json

**Comment by jwu** [comment]
My Log:

```
johnny@firebox-johnny-wu:~/fireball/ed$npm install
npm WARN package.json editor-framework@0.3.15 license should be a valid SPDX license expression

> editor-framework@0.3.15 preinstall /Users/johnny/fireball/ed
> npm install npmconf@2.1.2 && node ./utils/pre-install-npm.js

npm WARN package.json editor-framework@0.3.15 license should be a valid SPDX license expression
npmconf@2.1.2 node_modules/npmconf
├── uid-number@0.0.5
├── ini@1.3.4
├── inherits@2.0.1
├── semver@4.3.6
├── once@1.3.2 (wrappy@1.0.1)
├── osenv@0.1.3 (os-tmpdir@1.0.1, os-homedir@1.0.1)
├── nopt@3.0.3 (abbrev@1.0.7)
├── config-chain@1.1.9 (proto-list@1.2.4)
└── mkdirp@0.5.1 (minimist@0.0.8)
Do you want to use mirror in China to download Electron and other dependencies? (y/n) : n
 
> fsevents@0.3.8 install /Users/johnny/fireball/ed/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node: Finished
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  SOLINK_MODULE(target) Release/fse.node: Finished
\
> nodegit@0.4.1 install /Users/johnny/fireball/ed/node_modules/firedoc/node_modules/nodegit
> node lifecycleScripts/install

[nodegit] Fetching binary from S3.
[nodegit] Completed installation successfully.
npm WARN prefer global firedoc@1.9.2 should be installed with -g

> editor-framework@0.3.15 install /Users/johnny/fireball/ed
> gulp bootstrap && bower install && gulp npm-rebuild && gulp update

[11:12:06] Using gulpfile ~/fireball/ed/gulpfile.js
[11:12:06] Starting 'bootstrap'...
[11:12:06] Starting 'install-builtin'...
git clone https://github.com/fireball-packages/console builtin/console in 
git clone https://github.com/fireball-packages/ipc-debugger builtin/ipc-debugger in 
git clone https://github.com/fireball-packages/package-manager builtin/package-manager in 
git clone https://github.com/fireball-packages/tester builtin/tester in 
git clone https://github.com/fireball-packages/ui-kit builtin/ui-kit in 
[11:12:06] Starting 'install-shared-packages'...
git clone https://github.com/fireball-packages/benchmark benchmark in 
git clone https://github.com/fireball-packages/package-examples package-examples in 
Cloning into 'builtin/console'...

Cloning into 'builtin/ipc-debugger'...

Cloning into 'builtin/package-manager'...

Cloning into 'builtin/tester'...

Cloning into 'builtin/ui-kit'...

Cloning into 'benchmark'...

Cloning into 'package-examples'...

Shared packages installation complete!
[11:12:08] Finished 'install-shared-packages' after 2.32 s
Builtin packages installation complete!
[11:12:09] Finished 'install-builtin' after 3.01 s
[11:12:09] Starting 'update-electron'...
[11:12:09] Starting 'setup-mirror'...
[11:12:09] Finished 'setup-mirror' after 376 μs
[11:12:09] Starting 'install-electron'...
npm WARN package.json editor-framework@0.3.15 license should be a valid SPDX license expression
\
> electron-prebuilt@0.30.0 postinstall /Users/johnny/fireball/ed/node_modules/electron-prebuilt
> node install.js

Downloading Electron v0.30.5
electron-prebuilt@0.30.0 node_modules/electron-prebuilt
├── extract-zip@1.0.3 (debug@0.7.4, minimist@0.1.0, async@0.9.0, mkdirp@0.5.0, yauzl@2.3.1, through2@0.6.3, concat-stream@1.5.0)
└── electron-download@1.0.8 (path-exists@1.0.0, home-path@0.1.2, mkdirp@0.5.1, debug@2.2.0, mv@2.1.1, nugget@1.5.4)
[11:12:21] Finished 'install-electron' after 13 s
[11:12:21] Starting 'electron-to-bin'...
copying electron from: node_modules/electron-prebuilt/dist
Electron v0.30.5 has been download to bin/electron folder
[11:12:22] Finished 'electron-to-bin' after 624 ms
[11:12:22] Finished 'update-electron' after 14 s
[11:12:22] Finished 'bootstrap' after 17 s
bower not-cached    git://github.com/web-animations/web-animations-js.git#master
bower resolve       git://github.com/web-animations/web-animations-js.git#master
bower cached        git://github.com/Polymer/polymer.git#1.1.2
bower validate      1.1.2 against git://github.com/Polymer/polymer.git#^1.1.1
bower cached        git://github.com/PolymerElements/iron-behaviors.git#1.0.7
bower validate      1.0.7 against git://github.com/PolymerElements/iron-behaviors.git#^1.0.0
bower cached        git://github.com/PolymerElements/iron-input.git#1.0.5
bower validate      1.0.5 against git://github.com/PolymerElements/iron-input.git#^1.0.0
bower cached        git://github.com/PolymerElements/iron-flex-layout.git#1.0.3
bower validate      1.0.3 against git://github.com/PolymerElements/iron-flex-layout.git#^1.0.0
bower cached        git://github.com/PolymerElements/iron-selector.git#1.0.2
bower validate      1.0.2 against git://github.com/PolymerElements/iron-selector.git#^1.0.0
bower cached        git://github.com/ccampbell/mousetrap.git#1.5.2
bower validate      1.5.2 against git://github.com/ccampbell/mousetrap.git#1.5.2
bower checkout      web-animations-js#master
bower cached        git://github.com/PolymerElements/iron-validatable-behavior.git#1.0.4
bower validate      1.0.4 against git://github.com/PolymerElements/iron-validatable-behavior.git#^1.0.0
bower new           version for git://github.com/PolymerElements/iron-behaviors.git#^1.0.0
bower resolve       git://github.com/PolymerElements/iron-behaviors.git#^1.0.0
bower download      https://github.com/PolymerElements/iron-behaviors/archive/v1.0.8.tar.gz
bower cached        git://github.com/chaijs/chai.git#2.3.0
bower validate      2.3.0 against git://github.com/chaijs/chai.git#2.3.0
bower cached        git://github.com/FortAwesome/Font-Awesome.git#4.3.0
bower validate      4.3.0 against git://github.com/FortAwesome/Font-Awesome.git#4.3.0
bower cached        git://github.com/mochajs/mocha.git#2.2.5
bower validate      2.2.5 against git://github.com/mochajs/mocha.git#2.2.5
bower cached        git://github.com/wout/svg.js.git#2.0.5
bower validate      2.0.5 against git://github.com/wout/svg.js.git#2.0.5
bower cached        git://github.com/adamwdraper/Numeral-js.git#1.5.3
bower validate      1.5.3 against git://github.com/adamwdraper/Numeral-js.git#1.5.3
bower cached        git://github.com/HubSpot/pace.git#1.0.2
bower validate      1.0.2 against git://github.com/HubSpot/pace.git#1.0.2
bower cached        git://github.com/PolymerElements/iron-meta.git#1.0.3
bower validate      1.0.3 against git://github.com/PolymerElements/iron-meta.git#^1.0.0
bower cached        git://github.com/GoodBoyDigital/pixi.js.git#3.0.6
bower validate      3.0.6 against git://github.com/GoodBoyDigital/pixi.js.git#3.0.6
bower cached        git://github.com/Polymer/webcomponentsjs.git#0.7.11
bower validate      0.7.11 against git://github.com/Polymer/webcomponentsjs.git#^0.7.2
bower extract       iron-behaviors#^1.0.0 archive.tar.gz
bower invalid-meta  iron-behaviors is missing "ignore" entry in bower.json
bower resolved      git://github.com/PolymerElements/iron-behaviors.git#1.0.8
bower cached        git://github.com/PolymerElements/iron-a11y-keys-behavior.git#1.0.5
bower validate      1.0.5 against git://github.com/PolymerElements/iron-a11y-keys-behavior.git#^1.0.0
bower resolved      git://github.com/web-animations/web-animations-js.git#28e527353b
bower new           version for git://github.com/Polymer/webcomponentsjs.git#^0.7.2
bower resolve       git://github.com/Polymer/webcomponentsjs.git#^0.7.2
bower download      https://github.com/Polymer/webcomponentsjs/archive/v0.7.12.tar.gz
bower extract       webcomponentsjs#^0.7.2 archive.tar.gz
bower resolved      git://github.com/Polymer/webcomponentsjs.git#0.7.12
bower install       iron-input#1.0.5
bower install       iron-flex-layout#1.0.3
bower install       polymer#1.1.2
bower install       iron-selector#1.0.2
bower install       mousetrap#1.5.2
bower install       iron-validatable-behavior#1.0.4
bower install       mocha#2.2.5
bower install       numeral#1.5.3
bower install       chai#2.3.0
bower install       svg.js#2.0.5
bower install       fontawesome#4.3.0
bower install       iron-behaviors#1.0.8
bower install       web-animations-js#28e527353b
bower install       pace#1.0.2
bower install       iron-meta#1.0.3
bower install       iron-a11y-keys-behavior#1.0.5
bower install       pixi#3.0.6
bower install       webcomponentsjs#0.7.12

iron-input#1.0.5 bower_components/iron-input
├── iron-validatable-behavior#1.0.4
└── polymer#1.1.2

iron-flex-layout#1.0.3 bower_components/iron-flex-layout
└── polymer#1.1.2

polymer#1.1.2 bower_components/polymer
└── webcomponentsjs#0.7.12

iron-selector#1.0.2 bower_components/iron-selector
└── polymer#1.1.2

mousetrap#1.5.2 bower_components/mousetrap

iron-validatable-behavior#1.0.4 bower_components/iron-validatable-behavior
├── iron-meta#1.0.3
└── polymer#1.1.2

mocha#2.2.5 bower_components/mocha

numeral#1.5.3 bower_components/numeral

chai#2.3.0 bower_components/chai

svg.js#2.0.5 bower_components/svg.js

fontawesome#4.3.0 bower_components/fontawesome

iron-behaviors#1.0.8 bower_components/iron-behaviors
├── iron-a11y-keys-behavior#1.0.5
└── polymer#1.1.2

web-animations-js#28e527353b bower_components/web-animations-js

pace#1.0.2 bower_components/pace

iron-meta#1.0.3 bower_components/iron-meta
└── polymer#1.1.2

iron-a11y-keys-behavior#1.0.5 bower_components/iron-a11y-keys-behavior
└── polymer#1.1.2

pixi#3.0.6 bower_components/pixi

webcomponentsjs#0.7.12 bower_components/webcomponentsjs
[11:12:33] Using gulpfile ~/fireball/ed/gulpfile.js
[11:12:33] Starting 'npm-rebuild'...
rebuilding native modules: 
node_modules/chokidar/node_modules/fsevents,node_modules/firedoc/node_modules/nodegit
module.js:339
    throw err;
          ^
Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at [eval]:1:1
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:431:26)
    at evalScript (node.js:561:25)
    at startup (node.js:88:9)
gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1009:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/iojs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--target=0.30.5" "--arch=x64" "--dist-url=https://atom.io/download/atom-shell"
gyp ERR! cwd /Users/johnny/fireball/ed/node_modules/firedoc/node_modules/nodegit
gyp ERR! node -v v2.1.0
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node: Finished
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  SOLINK_MODULE(target) Release/fse.node: Finished
[11:12:36] Finished 'npm-rebuild' after 3.1 s
[11:12:37] Using gulpfile ~/fireball/ed/gulpfile.js
[11:12:37] Starting 'update'...
[11:12:37] Starting 'setup-branch'...
Setup submodule branch local setting. You can change "local-setting.json" to specify your branches.
[11:12:37] Finished 'setup-branch' after 2.22 ms
[11:12:37] Starting 'update-editor-framework'...
git pull https://github.com/fireball-x/editor-framework.git master in ./
From https://github.com/fireball-x/editor-framework
 * branch            master     -> FETCH_HEAD

Already up-to-date.
```

**Comment by nantas** [comment]
related issue: https://github.com/nodejs/nan/issues/320
https://github.com/npm/npm/issues/5082
