### ISSUE TITLE
Unable to install either via npm command-line or through a package dependency

### ISSUE THREAD

**Issue by dekarguy** [fireball-x/editor-framework#63]
I am trying to follow the steps in the readme, and I get to the step of `npm install fireball-x/editor-framework`

It seems to go fine until the gulp step of `update-editor-framework` when I get this output

```
[13:13:36] Starting 'update-editor-framework'...
git pull https://github.com/fireball-x/editor-framework.git master in ./
fatal: Not a git repository (or any of the parent directories): .git

node.js:609
        throw new TypeError('invalid pid');
              ^
TypeError: invalid pid
    at process.kill (node.js:609:15)
    at Socket.<anonymous> (D:\sample\node_modules\editor-framework\utils\libs\git.js:21:21)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at Pipe.onread (net.js:538:20)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "fireball-x/editor-framework"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! editor-framework@0.3.16 install: `gulp bootstrap && bower install && gulp npm-rebuild && gulp update`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the editor-framework@0.3.16 install script 'gulp bootstrap && bower install && gulp npm-rebuild && gulp update'.
npm ERR! This is most likely a problem with the editor-framework package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp bootstrap && bower install && gulp npm-rebuild && gulp update
npm ERR! You can get their info via:
npm ERR!     npm owner ls editor-framework
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\sample\Research\ef\npm-debug.log
```

I also get the same when trying to use editor-framework as a dependency in a package

```
	"dependencies": {
		"angular": "~1.4.3",
		"editor-framework": "git+https://github.com/fireball-x/editor-framework"
	},
```

**Comment by jwu** [comment]
@dekarguy thanks for your report, i just fix the problem.

**Comment by dekarguy** [comment]
Thank you for the quick fix. The only other issue I'm seeing on doing it via an npm install or a package dependency is that it always asks this: `Do you want to use mirror in China to download Electron and other dependencies? (y/n) :`

Is it possible to get a configuration that can run without user input for automated builds?

**Comment by jwu** [comment]
@dekarguy I just remove the mirror asks, please try it again.
