### ISSUE TITLE
error installing

### ISSUE THREAD

**Issue by gbaumgart** [fireball-x/editor-framework#81]
i tried now git clone and npm install npm install fireball-x/editor-framework but both get stuck here:

Cloning into 'builtin/ui-kit'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
[10:54:54] 'update-builtin' errored after 6.8 s
[10:54:54] Error: Failed to exec git clone git@github.com:fireball-packages/ipc-debugger.git builtin/ipc-debugger
    at ChildProcess.<anonymous> (/PMaster/projects/x4mm/node_modules/editor-framework/utils/libs/git.js:36:14)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:797:12)
[10:54:54] 'bootstrap' errored after 6.81 s
[10:54:54] Error: Failed to exec git clone git@github.com:fireball-packages/ipc-debugger.git builtin/ipc-debugger
    at ChildProcess.<anonymous> (/PMaster/projects/x4mm/node_modules/editor-framework/utils/libs/git.js:36:14)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:797:12)
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
[10:54:54] 'update-hosts' errored after 6.85 s
[10:54:54] Error: Failed to exec git clone git@github.com:fireball-packages/package-examples.git package-examples
    at ChildProcess.<anonymous> (/PMaster/projects/x4mm/node_modules/editor-framework/utils/libs/git.js:36:14)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:797:12)
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
npm ERR! editor-framework@0.3.17 install: `gulp bootstrap && bower install && gulp npm-rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the editor-framework@0.3.17 install script.
npm ERR! This is most likely a problem with the editor-framework package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp bootstrap && bower install && gulp npm-rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls editor-framework
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.13.0-65-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "fireball-x/editor-framework"
npm ERR! cwd /PMaster/projects/x4mm/subs
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /PMaster/projects/x4mm/subs/npm-debug.log
npm ERR! not ok code 0
mc007@mcdev:/PMaster/projects/x4mm/subs$ 

its asking me from some github password (dialog)

ubuntu-64-14

**Comment by jwu** [comment]
hi gbaumgart, this is because I use ssh for cloning git repo. So you need to make sure your ssh-key setup correctly in your machine with Github

**Comment by gbaumgart** [comment]
too bad but no, please fix it, i will try later again :-)
